export const FETCH_SPELLS_START = 'FETCH_SPELLS_START';
export const FETCH_SPELLS_SUCCESS = 'FETCH_SPELLS_SUCCESS';
export const FETCH_SPELLS_FAILURE = 'FETCH_SPELLS_FAILURE';
export const FILTER_SPELLS = 'FILTER_SPELLS';

